#ifndef GL_EXT_H
#define GL_EXT_H

#include "engine/gl_compat.h"

typedef enum {
    GLEXT_NONE = -1,
    GLEXT_SHADER_OBJECTS,
    GLEXT_VERTEX_SHADER,
    GLEXT_FRAGMENT_SHADER,
    GLEXT_VERTEX_BUFFER_OBJECT,
    GLEXT_FRAMEBUFFER_OBJECT,
    GLEXT_FRAMEBUFFER_MULTISAMPLE,
    GLEXT_FRAMEBUFFER_BLIT,
    GLEXT_TEXTURE_FLOAT,
    GLEXT_TEXTURE_SRGB,
    GLEXT_TEXTURE_NON_POWER_OF_TWO,
    GLEXT_TEXTURE_FILTER_ANISOTROPIC,
    GLEXT_COUNT
} GlExtension;

// first column: the extension an entry point needs, GLEXT_NONE for GL 2.0 core
#define GL_ENTRY_POINTS(X) \
    X(GLEXT_NONE, PFNGLACTIVETEXTUREPROC, glActiveTexture) \
    X(GLEXT_NONE, PFNGLGENBUFFERSPROC, glGenBuffers) \
    X(GLEXT_NONE, PFNGLDELETEBUFFERSPROC, glDeleteBuffers) \
    X(GLEXT_NONE, PFNGLBINDBUFFERPROC, glBindBuffer) \
    X(GLEXT_NONE, PFNGLBUFFERDATAPROC, glBufferData) \
    X(GLEXT_NONE, PFNGLBUFFERSUBDATAPROC, glBufferSubData) \
    X(GLEXT_NONE, PFNGLCREATESHADERPROC, glCreateShader) \
    X(GLEXT_NONE, PFNGLDELETESHADERPROC, glDeleteShader) \
    X(GLEXT_NONE, PFNGLSHADERSOURCEPROC, glShaderSource) \
    X(GLEXT_NONE, PFNGLCOMPILESHADERPROC, glCompileShader) \
    X(GLEXT_NONE, PFNGLGETSHADERIVPROC, glGetShaderiv) \
    X(GLEXT_NONE, PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog) \
    X(GLEXT_NONE, PFNGLCREATEPROGRAMPROC, glCreateProgram) \
    X(GLEXT_NONE, PFNGLDELETEPROGRAMPROC, glDeleteProgram) \
    X(GLEXT_NONE, PFNGLATTACHSHADERPROC, glAttachShader) \
    X(GLEXT_NONE, PFNGLDETACHSHADERPROC, glDetachShader) \
    X(GLEXT_NONE, PFNGLLINKPROGRAMPROC, glLinkProgram) \
    X(GLEXT_NONE, PFNGLUSEPROGRAMPROC, glUseProgram) \
    X(GLEXT_NONE, PFNGLGETPROGRAMIVPROC, glGetProgramiv) \
    X(GLEXT_NONE, PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog) \
    X(GLEXT_NONE, PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation) \
    X(GLEXT_NONE, PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation) \
    X(GLEXT_NONE, PFNGLUNIFORM1IPROC, glUniform1i) \
    X(GLEXT_NONE, PFNGLUNIFORM1FPROC, glUniform1f) \
    X(GLEXT_NONE, PFNGLUNIFORM2FPROC, glUniform2f) \
    X(GLEXT_NONE, PFNGLUNIFORM3FPROC, glUniform3f) \
    X(GLEXT_NONE, PFNGLUNIFORM4FPROC, glUniform4f) \
    X(GLEXT_NONE, PFNGLUNIFORM1IVPROC, glUniform1iv) \
    X(GLEXT_NONE, PFNGLUNIFORM1FVPROC, glUniform1fv) \
    X(GLEXT_NONE, PFNGLUNIFORM2FVPROC, glUniform2fv) \
    X(GLEXT_NONE, PFNGLUNIFORM3FVPROC, glUniform3fv) \
    X(GLEXT_NONE, PFNGLUNIFORM4FVPROC, glUniform4fv) \
    X(GLEXT_NONE, PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv) \
    X(GLEXT_NONE, PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv) \
    X(GLEXT_NONE, PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer) \
    X(GLEXT_NONE, PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray) \
    X(GLEXT_NONE, PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLGENFRAMEBUFFERSEXTPROC, glGenFramebuffersEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLDELETEFRAMEBUFFERSEXTPROC, glDeleteFramebuffersEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLBINDFRAMEBUFFEREXTPROC, glBindFramebufferEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLFRAMEBUFFERTEXTURE2DEXTPROC, glFramebufferTexture2DEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC, glFramebufferRenderbufferEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC, glCheckFramebufferStatusEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLGENRENDERBUFFERSEXTPROC, glGenRenderbuffersEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLDELETERENDERBUFFERSEXTPROC, glDeleteRenderbuffersEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLBINDRENDERBUFFEREXTPROC, glBindRenderbufferEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLRENDERBUFFERSTORAGEEXTPROC, glRenderbufferStorageEXT) \
    X(GLEXT_FRAMEBUFFER_OBJECT, PFNGLGENERATEMIPMAPEXTPROC, glGenerateMipmapEXT) \
    X(GLEXT_FRAMEBUFFER_MULTISAMPLE, PFNGLRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC, glRenderbufferStorageMultisampleEXT) \
    X(GLEXT_FRAMEBUFFER_BLIT, PFNGLBLITFRAMEBUFFEREXTPROC, glBlitFramebufferEXT)

#ifndef __APPLE__
#define GL_EXT_DECLARE(gate, type, name) extern type name;
GL_ENTRY_POINTS(GL_EXT_DECLARE)
#undef GL_EXT_DECLARE
#endif

int gl_ext_load(const char **missing);
void gl_ext_print_status(void);
int gl_ext_present(GlExtension extension);
int gl_ext_list_has(const char *list, const char *name);
void gl_ext_set_swap_interval(int interval);

#endif
