#!/usr/bin/env python3
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = 'assets/raw/fonts/b612_mono/B612Mono-Regular.ttf'
ATLAS = 'assets/generated/hud_font.png'
METRICS = 'assets/generated/hud_font.txt'

FIRST_CODE = 32
LAST_CODE = 126
PIXEL_SIZE = 32
PADDING = 1
# the opaque block the engine samples for boxes and lines, wide enough that filtering stays inside it
SOLID_SIZE = 4
ATLAS_SIZES = [64, 128, 256, 512, 1024, 2048]


def rasterize(font):
    glyphs = []
    for code in range(FIRST_CODE, LAST_CODE + 1):
        character = chr(code)
        left, top, right, bottom = font.getbbox(character)
        image = Image.new('L', (right - left, bottom - top), 0)
        if image.width > 0 and image.height > 0:
            ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255)
        # the box the font reports is as wide as the advance, so the ink is cut out of it to save atlas room
        ink = image.getbbox() or (0, 0, 0, 0)
        image = image.crop(ink)
        left += ink[0]
        top += ink[1]
        glyphs.append({'code': code, 'image': image, 'bearing_x': left, 'bearing_y': top,
                       'advance': round(font.getlength(character))})
    return glyphs


# shelf packing in code order: a row at a time, every box surrounded by its padding
def pack(boxes, width, height):
    places = []
    x = PADDING
    y = PADDING
    row = 0
    for box_width, box_height in boxes:
        if x + box_width + PADDING > width:
            x = PADDING
            y += row + PADDING
            row = 0
        if y + box_height + PADDING > height:
            return None
        places.append((x, y))
        x += box_width + PADDING
        row = max(row, box_height)
    return places


def choose_atlas(boxes):
    for size in ATLAS_SIZES:
        places = pack(boxes, size, size)
        if places is not None:
            return size, size, places
    raise SystemExit('the glyphs do not fit in the largest atlas')


def compose(glyphs, places, solid, width, height):
    coverage = Image.new('L', (width, height), 0)
    coverage.paste(255, (solid[0], solid[1], solid[0] + SOLID_SIZE, solid[1] + SOLID_SIZE))
    for glyph, place in zip(glyphs, places):
        coverage.paste(glyph['image'], place)
    # white under the coverage, so a filtered or mipmapped sample never pulls black into a glyph edge
    atlas = Image.new('RGBA', (width, height), (255, 255, 255, 0))
    atlas.putalpha(coverage)
    return atlas


def write_metrics(path, glyphs, places, solid, width, height, line_height):
    with open(path, 'w', newline='\n') as out:
        out.write('# generated by tools/gen-font-atlas.py, do not edit by hand\n')
        out.write(f'atlas {width} {height}\n')
        out.write(f'size {PIXEL_SIZE}\n')
        out.write(f'line {line_height}\n')
        out.write(f'solid {solid[0] + SOLID_SIZE // 2} {solid[1] + SOLID_SIZE // 2}\n')
        for glyph, place in zip(glyphs, places):
            out.write(f'glyph {glyph["code"]} {place[0]} {place[1]} {glyph["image"].width} {glyph["image"].height} '
                      f'{glyph["bearing_x"]} {glyph["bearing_y"]} {glyph["advance"]}\n')


def main():
    os.chdir(ROOT)
    font = ImageFont.truetype(FONT, PIXEL_SIZE)
    ascent, descent = font.getmetrics()
    glyphs = rasterize(font)
    # the block for boxes and lines is packed first, so it always finds room
    boxes = [(SOLID_SIZE, SOLID_SIZE)] + [(glyph['image'].width, glyph['image'].height) for glyph in glyphs]
    width, height, places = choose_atlas(boxes)
    solid = places.pop(0)

    os.makedirs(os.path.dirname(ATLAS), exist_ok=True)
    compose(glyphs, places, solid, width, height).save(ATLAS)
    write_metrics(METRICS, glyphs, places, solid, width, height, ascent + descent)
    print(f'wrote {ATLAS} at {width}x{height} and {METRICS} with {len(glyphs)} glyphs')


if __name__ == '__main__':
    main()
